name: flop_benchmark
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - r-base
  - r-bayesbio
  - python=3.10
  - openjdk
  - r-tidyverse
  - pip
  - r-cowplot
  - r-egg
  - r-fossil
  - r-ggdendro
  - r-ggdist
  - r-ggpp
  - r-testthat
  - bioconductor-edger
  - bioconductor-deseq2
  - bioconductor-vsn
  - bioconductor-org.hs.eg.db
  - pip:
    - decoupler
    - omnipath