---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggplot2)
library(nlme)
library(rstudioapi)
library(ggdendro)
library(viridis)
library(fossil)

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
workdir <- dirname(rstudioapi::getActiveDocumentContext()$path)

```

## Data collection
```{r}
cell_lines <- list.files('./results/dc_output/', pattern='_.*\\.tsv$') %>% sub(pattern='_.*\\.tsv', replacement='') %>% unique()
resources <- list.files('./dc_resources/', pattern='__source.tsv$') %>% sub(pattern='__source.tsv$', replacement='') %>% unique()
merged_data <- tibble()
statparams <- c('stat', 'logFC')
for(statparam in statparams){
  for(cell_line in cell_lines){
    for(resource in resources){
      file_list <- list.files('./results/dc_output/', pattern=paste(cell_line, '_.*__', statparam,'__cons__', resource, '__decoupleroutput.tsv', sep='')) %>% paste('./results/dc_output/', ., sep='')
      for(file in file_list) {
        file_data <- read_tsv(file, show_col_types=FALSE) %>% 
          separate(...1, into=c('cell_line_treatment','norm', 'diffexp', 'dcmethod'), sep='__', remove=FALSE) %>%
          separate(cell_line_treatment, into=c('cell_line', 'treatment'), sep='_') %>% 
          select(-dcmethod) %>% 
          pivot_longer(cols=c(6:ncol(.)), names_to = 'items', values_to = 'scores') %>% 
          mutate(statparam=!!statparam, resource=!!resource)
        merged_data <- rbind(merged_data, file_data)
      }
    }
  }
}

```

```{r}
merged_data <- merged_data %>% mutate(pipeline=paste(norm, diffexp, sep = '+'))
pipelines <- merged_data %>% distinct(pipeline) %>% pull()
items <- merged_data %>% distinct(items) %>% pull()
```


```{r}
source('dendro_helpers.R')
statparam='stat'
```


```{r}
clustering_k <- function(merged_data, k){
  cluster_results <- list()
  for(resource in resources){
    for (pipeline in pipelines){
      filt_data <- merged_data %>% 
        filter(pipeline==!!pipeline, statparam==!!statparam, resource==!!resource) %>% 
        mutate(...1=sub(pattern = '__.*', '', ...1)) %>% 
        rename(id=...1)
      numeric_data <- filt_data %>% pivot_wider(names_from=items, values_from=scores,id_cols = id) %>% column_to_rownames('id')
      cluster <- numeric_data %>% dist() %>% hclust(., 'ave')
      hcdata <- dendro_data_k(cluster, k)
      cluster_results[[resource]][[pipeline]] <- hcdata
    }
  }
  return(cluster_results)
}
```

```{r}
plotdirectory <- paste(workdir, '/results/plots/', sep='')
dir.create(plotdirectory, showWarnings = FALSE)
```


```{r, fig.height=10, fig.width=10}
cluster_results <- clustering_k(merged_data, 32)
for(resource in resources){
  for (pipeline in pipelines){
    filt_data <- merged_data %>% 
      filter(pipeline==!!pipeline, statparam==!!statparam, resource==!!resource) %>% 
      mutate(...1=sub(pattern = '__.*', '', ...1)) %>% 
      rename(id=...1)
    metadata <- filt_data %>% select(-items, -scores) %>% distinct() %>% column_to_rownames(.,'id')
    
    hcdata <- cluster_results[[resource]][[pipeline]]
    p <- plot_ggdendro(hcdata,
                     metadata,
                     'cell_line',
                     fan         = TRUE,
                     label.size  = 1.5,
                     nudge.label = 0.15,
                     expand.y    = 0.8,
                     nclust=11)
  
    
    p <- p + theme_cowplot() + theme(line = element_blank(),
                                     axis.ticks = element_blank(),
                                     axis.title = element_blank(),
                                     axis.text = element_blank())
    
    dendro <- p + geom_point(data     = metadata, 
                   aes(x    = match(rownames(metadata), hcdata$labels$label),
                       y    = -0.5,
                       fill = as.factor(treatment)),
                   size     = 1.5,
                   shape    = 21,
                   show.legend = FALSE) +
      scale_fill_viridis(discrete = TRUE)
    plotname=paste(plotdirectory, paste(resource, pipeline,'fan_dendrogram.png', sep = '__' ), sep='')
    ggsave(filename=plotname, plot=dendro, height = 10, width=10)
  }
}
```


```{r}
k_values <-seq(from = 1, to = 32, by = 1)
rand_results_long <- tibble()
for(resource in resources){
  for(i in k_values){
    rand_results <- matrix(nrow = 5, ncol = 5, 0, dimnames = list(pipelines, pipelines)) %>% as.data.frame()
    row.names(rand_results)
    cluster_results <- clustering_k(merged_data, i)
    for(pipeline1 in pipelines){
      for(pipeline2 in pipelines){
        rand_result <- rand.index(cluster_results[[resource]][[pipeline1]]$segments$clust, cluster_results[[resource]][[pipeline2]]$segments$clust)
        rand_results[pipeline1, pipeline2] <- rand_result
      }
    }
    
    rand_results_long <- rand_results %>% 
      rownames_to_column(var='pipeline1') %>% 
      pivot_longer(.,cols=-pipeline1, names_to = 'pipeline2', values_to = 'scores') %>%
      mutate(k=i) %>%
      rowwise() %>%
      mutate(diff = paste(sort(c(pipeline1, pipeline2))[1], sort(c(pipeline1, pipeline2))[2],sep='_vs_'), resource=resource) %>% 
      filter(pipeline1 != pipeline2) %>% 
      distinct(diff,.keep_all = TRUE) %>%
      rbind(., rand_results_long)
  }
}
saveRDS(rand_results_long, './results/rand_results_long.Rds')
rand_results_long <- read_rds('./results/rand_results_long.Rds')
```



```{r}
boxplots <- ggplot(rand_results_long, aes(x=diff, y=scores, fill=diff)) +
  geom_boxplot() +
  ylim(0.5,1) +
  theme(axis.text.x = element_text(angle=45, vjust = 1, hjust=1),
        plot.margin=margin(10,10,10,30))
boxplots
```



```{r}
boxplot_k <- ggplot(rand_results_long, aes(x=factor(k), y=scores)) +
  ggdist::stat_halfeye(
    width = 0.8,
    justification = -.2, 
    point_colour = NA
  ) + 
  geom_boxplot(
    width = .15, 
    outlier.shape = NA
  ) +
  geom_point(
    position=ggpp::position_jitternudge(
      x=-0.2,
      width=0.07,
      nudge.from = 'jittered'
    ),
    size=0.6
  ) +
  xlab('Number of K clusters')+
  ylab('Rand Index score')+
  scale_x_discrete(labels=c(rep("", 4),"5",rep("", 4), "10",rep("", 4),"15",rep("", 4), "20",rep("", 4), "25",rep("", 4), "30",rep("", 2)))+
  cowplot::theme_cowplot()+
  theme(axis.text.x = element_text(vjust = 0, hjust=0.5),
        plot.margin=margin(10,10,10,20),
        legend.position='none',
        strip.background = element_blank(),
        strip.text = element_blank(),
        panel.spacing = unit(2,'lines')
        ) +
  
  facet_grid(rows = vars(resource), labeller=labeller(
    resource = c(dorothea = 'DoRothEA', msigdb_hallmarks = 'MSigDB Hallmarks', progeny='PROGENy')
  ))
```

```{r}
boxplot_pipelines <- ggplot(rand_results_long, aes(x=diff, y=scores, fill=diff)) +
  ggdist::stat_halfeye(
    adjust = .5, 
    width = .5, 
    .width = 0, 
    justification = -.2, 
    point_colour = NA
  ) + 
  geom_boxplot(
    width = .15, 
    outlier.shape = NA
  ) +
  geom_point(
    aes(color=factor(diff)),
    position=ggpp::position_jitternudge(
      x=-0.3,
      width=0.1,
      nudge.from = 'jittered'
    ), size=0.6
  )+
  ylab('Rand Index score')+
  cowplot::theme_cowplot()+
  theme(axis.text.x = element_text(angle=45, vjust = 1, hjust=1),
        axis.title.x = element_blank(),
        plot.margin=margin(10,10,10,30),
        axis.text.y.left = element_blank(), 
        axis.title.y = element_blank(),
        legend.position='none',
        panel.spacing = unit(2,'lines')
        ) +
  
  facet_grid(rows = vars(resource), labeller=labeller(
    resource = c(dorothea = 'DoRothEA', msigdb_hallmarks = 'MSigDB Hallmarks', progeny='PROGENy')
  ))


```

```{r}
library(cowplot)
aligned_plots <- egg::ggarrange(boxplot_k, boxplot_pipelines, ncol = 2, widths = c(2,1))
final <- ggdraw() + draw_plot(aligned_plots, 0, 0, 1, 1) +
  draw_plot_label('A', 0, 1)+
  draw_plot_label('B', 0.65, 1)
save_plot(filename = './results/plots/rand_index_plots.png', plot = final, device='png', dpi=300, base_height=7.5, base_width =10)
```




```{r}
rand_pipelines <- function(rand_results_long, resource){
  rand_results_long_filt <- rand_results_long %>%
    as_tibble() %>%
    filter(resource==!!resource)
  boxplot <- ggplot(rand_results_long_filt, aes(x=diff, y=scores, fill=diff)) +
    ggdist::stat_halfeye(
      adjust = .5, 
      width = .5, 
      .width = 0, 
      justification = -.2, 
      point_colour = NA
    ) + 
    geom_boxplot(
      width = .15, 
      outlier.shape = NA
    ) +
    geom_point(
      aes(color=factor(diff)),
      position=ggpp::position_jitternudge(
        x=-0.3,
        width=0.1,
        nudge.from = 'jittered'
      )
    ) +
    ylab('Rand Index score')+
    theme_cowplot() +
    theme(axis.text.x = element_text(angle=45, vjust = 1, hjust=1),
          axis.title.x = element_blank(),
          plot.margin=margin(10,10,10,50),
          legend.position='none')
  
  return(boxplot)
}
```


```{r}
rand_kvals <- function(rand_result_long){
  rand_results_long_filt <- rand_results_long %>%
    as_tibble()
  boxplot <- ggplot(rand_results_long_filt, aes(x=factor(k), y=scores, fill=factor(k))) +
    ggdist::stat_halfeye(
      adjust = .5, 
      width = .6, 
      .width = 0, 
      justification = -.2, 
      point_colour = NA
    ) + 
    geom_boxplot(
      width = .15, 
      outlier.shape = NA
    ) +
    geom_point(
      aes(color=factor(k)),
      position=ggpp::position_jitternudge(
        x=-0.3,
        width=0.1,
        nudge.from = 'jittered'
      )
    ) +
    coord_cartesian(xlim = c(1.2, NA), clip = "off")+
    xlab('Number of K clusters')+
    ylab('Rand Index score')+
    theme_cowplot() +
    theme(legend.position='none') +
    facet_grid(~resource)
  return(boxplot)
}
```

```{r, fig.width=15, fig.height=10}
for(resource in resources){
  plot_kvals <- rand_kvals(rand_results_long, resource)
  plot_pipelines <- rand_pipelines(rand_results_long, resource)
  
  aligned_plots <- egg::ggarrange(plot_kvals, plot_pipelines, nrow = 2)
  final <- ggdraw() + draw_plot(aligned_plots, 0, 0, 1, 1) + draw_plot_label('A', 0, 1) +
    draw_plot_label('B', 0, 0.57)
  filename <- paste(plotdirectory, resource, '_combined.png', sep='__')
  save_plot(filename, final, dpi=300, base_width=15, base_height=10)
}
```


```{r}
ind_plots <- character()
for(resource in resources){
  plot_kvals <- rand_kvals(rand_results_long)
  plot_pipelines <- rand_pipelines(rand_results_long, resource)
  
  aligned_plots[[resource]] <- egg::ggarrange(plot_kvals, plot_pipelines, ncol = 2)
}
ggdraw() + draw_plot(aligned_plots[['dorothea']],0,0,1,1)

final <- ggdraw() + draw_plot(aligned_plots, 0, 0, 1, 1) + draw_plot_label('A', 0, 1) +
  draw_plot_label('B', 0, 0.57)
filename <- paste(plotdirectory, resource, '_combined.png', sep='__')
```




















