---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggplot2)
library(nlme)
library(rstudioapi)
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

```

## Data collection
```{r}
cell_lines <- list.files('./results/', pattern='_.*\\.tsv$') %>% sub(pattern='_.*\\.tsv', replacement='') %>% unique()
merged_data <- tibble()
statparams <- c('stat', 'logFC')
for(statparam in statparams){
  for(cell_line in cell_lines){
    file_list <- list.files('./results/', pattern=paste(cell_line, '_.*__', statparam,'__cons__decoupleroutput.tsv', sep='')) %>% paste('./results/', ., sep='')
    for(file in file_list) {
      file_data <- read_tsv(file, show_col_types=FALSE) %>% separate(...1, into=c('cell_line_treatment','norm', 'diffexp', 'dcmethod'), sep='__', remove=FALSE) %>% separate(cell_line_treatment, into=c('cell_line', 'treatment'), sep='_') %>%
        pivot_longer(cols=c('Androgen':ncol(.)), names_to = 'pathway', values_to = 'scores') %>% select(-dcmethod) %>% mutate(statparam=!!statparam)
      merged_data <- rbind(merged_data, file_data)
    }
  }
}

```

```{r}
merged_data <- merged_data %>% mutate(pipeline=paste(norm, diffexp, sep = '+'))
pipelines <- merged_data %>% distinct(pipeline) %>% pull()
pathways <- merged_data %>% distinct(pathway) %>% pull()
```


```{r}
result_pipeline <- tibble()
anova_pipeline <- tibble()
for(statparam in statparams){
  for(cell_line in cell_lines){
    for(pathway in pathways){
      selected_data <- merged_data %>% filter(cell_line==!!cell_line) %>% filter(pathway==!!pathway) %>% filter(statparam==!!statparam)
      
      pipeline_model <- lme(scores ~ 0 + pipeline , data = selected_data, random = ~ 1 | treatment)
      
      result_iter <- pipeline_model %>% 
      summary() %>%
      .$tTable %>% 
      as.data.frame() %>% 
      rownames_to_column(var='ID') %>% 
      mutate(pipeline = sub('pipeline','',ID)) %>% 
      select(-ID) %>%
      as_tibble() %>% 
      mutate(cell_line=!!cell_line, pathway=!!pathway, statparam=!!statparam) %>%
      relocate(where(is.character), .before=where(is.numeric))
      
      anova_iter <- pipeline_model %>%
      anova() %>%
      as_tibble() %>%
      mutate(cell_line=!!cell_line, pathway=!!pathway, statparam=!!statparam) %>%
      relocate(where(is.character), .before=where(is.numeric))
      
      result_pipeline <- rbind(result_pipeline, result_iter)
      anova_pipeline <- rbind(anova_pipeline, anova_iter)
    }
  }
}
result_pipeline <- result_pipeline %>% rename(pval=`p-value`)
anova_pipeline <- anova_pipeline %>% rename(pval='p-value')
```



```{r, fig.width=8,fig.height=4}
ggplot(anova_pipeline, aes(cell_line, pathway), size=pval) +
  geom_point(aes(cell_line, pathway, colour = pval<0.05,size=-log(pval)), position = position_dodge(width = 0)) +
  scale_colour_manual(name = 'Significance (pvalue < 0.05)', values = setNames(c('red','darkgrey'),c(T, F)))+
  scale_size(name='-log(pvalue)')+
  xlab('Level') + 
  ylab('Pathways')+
  theme(axis.text.x = element_text(angle = 45,hjust=1,vjust=1)) +
  facet_grid(~statparam)
ggsave('scatterpvalspathway_pipeline.png',path='./results/', dpi=300)
```

```{r}
library(metap)
acrosspathways_results <- tibble()
acrosscell_results <- tibble()
for(cell_line in cell_lines){
  selected_data_meta <- anova_pipeline %>% 
    filter(cell_line==!!cell_line)
  stat_meta <- selected_data_meta %>% 
    filter(statparam=='stat') %>% pull(pval) %>% sumlog()
  logfc_meta <- selected_data_meta %>% 
    filter(statparam=='logFC') %>% 
    pull(pval) %>% 
    sumlog()
  acrosspathways_results <- c(stat_meta[1], stat_meta[2], stat_meta[3]) %>% 
    as_tibble() %>% 
    mutate(value=!!cell_line, statparam='stat', across='Across pathways') %>%
	 relocate(value, statparam) %>%
    rbind(acrosspathways_results,.)
  acrosspathways_results <- c(logfc_meta[1], logfc_meta[2], logfc_meta[3]) %>% 
    as_tibble() %>% 
    mutate(value=!!cell_line, statparam='logFC', across='Across pathways') %>% 
    relocate(value, statparam) %>%
    rbind(acrosspathways_results,.)
}

for(pathway in pathways){
  selected_data_meta <- anova_pipeline %>% 
    filter(pathway==!!pathway)
  stat_meta <- selected_data_meta %>% 
    filter(statparam=='stat') %>% pull(pval) %>% sumlog()
  logfc_meta <- selected_data_meta %>% 
    filter(statparam=='logFC') %>% 
    pull(pval) %>% 
    sumlog()
  acrosscell_results <- c(stat_meta[1], stat_meta[2], stat_meta[3]) %>% 
    as_tibble() %>% 
    mutate(value=!!pathway, statparam='stat', across='Across cell lines') %>%
	 relocate(value, statparam) %>%
    rbind(acrosscell_results,.)
  acrosscell_results <- c(logfc_meta[1], logfc_meta[2], logfc_meta[3]) %>% 
    as_tibble() %>% 
    mutate(value=!!pathway, statparam='logFC', across='Across cell lines') %>% 
    relocate(value, statparam) %>%
    rbind(acrosscell_results,.)
}

metanalysis_results <- rbind(acrosscell_results, acrosspathways_results)
```

```{r, fig.width=6,fig.height=2}
axis_titles <- data.frame(
  Species = c("Across cell lines", "Across pathways"),
  axis_title = c("Pathway", "Cell line")
)

ggplot(metanalysis_results, aes(value, statparam)) +
  geom_point(aes(value, statparam, colour = p<0.05,size=-log(p)), position = position_dodge(width = 0)) +
  scale_colour_manual(name = 'Significance (pvalue < 0.05)', values = setNames(c('red','darkgrey'),c(T, F)))+
  scale_size(name='-log(pvalue)')+
  xlab(' ') + 
  ylab('Method')+
  theme(axis.text.x = element_text(angle = 45,hjust=1,vjust=1)) +
  facet_grid(~across, scales = 'free_x')

ggsave('metanalysisacross_pipeline.png',path='./results/', dpi=300)
```


```{r}
library(pheatmap)
numeric_info <- merged_data %>% select(...1, pathway, scores, statparam) %>% filter(statparam=='stat') %>% select(-statparam) %>% pivot_wider(names_from = pathway, values_from = scores) %>% column_to_rownames(var='...1')  
annotations <- merged_data %>% select(1:5) %>% distinct() %>% column_to_rownames(var='...1')
heatmap <- pheatmap(numeric_info, annotation_row = annotations, main='stat', show_rownames=F, cellheight=0.5)
ggsave('heatmap_all.png', path='./results/', plot=heatmap, dpi=300, width=10, height=15, limitsize=FALSE)
```

```{r, fig.width=6,fig.height=6}
library(ComplexHeatmap)
Heatmap(numeric_info, name = "mat", row_split = annotations$norm, 
                    right_annotation = rowAnnotation(df=annotations),
                    show_row_names = FALSE)

```

